### ISSUE TITLE
Bot failed to detect PCT combined online

### ISSUE THREAD

**Issue by monty23monty** [vzdc-artcc/staffup-bot-v2#1]
When testing the bot, it picked up DCA_TWR online but did not show PCT_APP. 
![image](https://github.com/vZDC-ARTCC/staffup-bot-v2/assets/74265105/f5b69d01-ed89-4fd7-a45c-4612f0abd52b)
![image](https://github.com/vZDC-ARTCC/staffup-bot-v2/assets/74265105/42daea88-9b46-4863-9909-5080f66168f7)

**Comment by Pichukop** [comment]
Apologies for the error.
Are there any errors logs in you console(Cmd or Terminal) ?
If there are any can you give me the same ?

**Comment by monty23monty** [comment]
Hi, There are no Logs, just that the update request being sent.

**Comment by Pichukop** [comment]
Thanks For Pointing out the Issue.
i have succesfully fixed the bot, Update the bot with the latest version and the problem will be fixed.
Again Thanks for Pointing out the issue.
